apiVersion: v1
kind: Service
metadata: 
  name: jenkins-svc-lb
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - name: webport
      port: 35000
      targetPort: 8080
      protocol: TCP