apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  backoffLimit: 3
  template:
    metadata: job
    spec:
      containers:
        -name: job-pod
         image: alpine:3
         command:
           - sleep
           - 60 s