apiVersion: batch/v1
kind: Job
metadata:
  name: job
  namesapce: my-space
spec:
  backoffLimit: 3
  template:
    metadata: 
      name: job
      namesapce: my-space
    spec:
      containers:
        -name: job-pod
         image: alpine:3
         command:
           - sleep
           - 60 s