apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
  namespace: my-space
spec:
  backoffLimit: 3
  manualSelector: true
  selector:
    matchLabels:
      purpose: execute
  template:
    metadata:
      name: demo-pod
      namespace: my-space
      labels:
        purpose: execute
    spec:
      restartPolicy: OnFailure
      containers:
        - name: download
          image: alpine:3
          command:
            - sleep
            - 60s