apiVersion: batch/v1
kind: Job
metadata:
  name: job-alpine
  namespace: my-space
spec:
  template:
    metadata:
      name: demo-pod
      namespace: my-space
    spec:
      restartPolicy: OnFailure
      containers:
        - name: download
          image: alpine:3
          command:
            - sleep
            - 60s
  