apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: STANDARD
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pvc-claim
spec:
  containers:
    - name: mysql-pod
      image: mysql:latest
      env:
        -ame: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_USER
          value: qtdevops
        - name: MYSQL_PASSWORD
          value: qtdevops
      ports:
        - containerPort: 3306
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-vol
  volumes: 
    Volume:
      - name: mysql-vol
        persistentVolumeClaim:
          claimName: mysql-pvc
          readOnly: false