----
apiVersion: v1
kind: Service
metadata:
  name: zabbix-svc-lb
spec:
  type: LoadBalancer
  selector:
    app: Zabbix
    ver: "1.23"
  ports:
    - port: 35000
      name: webport
      targetPort: 80
      protocol: TCP