apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-deployment
spec:
  minReadySeconds: 10
  replicas: 4
  selector:
    matchLabels:
      app: zabbix
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: zabbix-Deploy
      labels:
        app: zabbix
        version: ol-6.0-latest
    spec:
      containers:
        - name: zabbix-pod
          image: zabbix/zabbix-server-mysql:ol-6.0-latest
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-svc-lb
spec:
  type: LoadBalancer
  selector:
    app: zabbix
    ver: "ol-6.0-latest"
  ports:
    - port: 35000
      name: webport
      targetPort: 80
      protocol: TCP