---
- name: apache installation on ubuntu
  hosts: all
  become: true
  tasks:
    - name: install apche2
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present